<?xml version='1.0'?>

<robot name="atom" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="robot_name" value="atom" />
	<!-- <xacro:property name="robot_chassis_mass" value="15"/> -->
	<xacro:property name="robot_chassis_mass" value="15"/>
	<xacro:property name="robot_chassis_length" value="0.2"/>
	<xacro:property name="robot_chassis_radius" value="0.25"/>
	<xacro:property name="robot_caster_wheel_radius" value="0.05"/>
	<xacro:property name="robot_caster_wheel_radius_collision" value="0.0499"/>

	<xacro:property name="robot_wheel_mass" value="3"/>
	<xacro:property name="robot_wheel_length" value="0.05"/>
	<xacro:property name="robot_wheel_radius" value="0.08"/>

	<!-- ========================================================================================== -->
	<!-- Scout Mini Version -->
    <xacro:property name="wheelbase" value="0.463951"/>
    <xacro:property name="track" value="0.416503"/>
    <xacro:property name="wheel_vertical_offset" value="-0.100998" />

	<!-- <xacro:property name="track" value="0.3426" />
    <xacro:property name="wheelbase" value="0.3181"/>
    <xacro:property name="wheel_vertical_offset" value="-0.160000047342231" /> -->

	<!-- <xacro:property name="wheelbase" value="0.3132556"/>
	<xacro:property name="track" value="0.4563536" />
	<xacro:property name="wheel_vertical_offset" value="-0.077" /> -->
	<!-- ========================================================================================== -->

    <xacro:include filename="$(find mando_gazebo)/urdf/scout_mini_wheel_1.xacro" />
    <xacro:include filename="$(find mando_gazebo)/urdf/scout_mini_wheel_2.xacro" />
    <xacro:include filename="$(find mando_gazebo)/urdf/scout_mini_wheel_3.xacro" />
    <xacro:include filename="$(find mando_gazebo)/urdf/scout_mini_wheel_4.xacro" />

	<!-- ========================================================================================== -->
	<!-- <xacro:property name="robot_mechaical_design_offset_x" value="0.015" />
	<xacro:property name="robot_mechaical_design_offset_y" value="0.0231316650320557" />
	<xacro:property name="robot_mechaical_design_offset_z" value="0" /> -->

	<xacro:property name="robot_mechaical_design_offset_x" value="0" />
	<xacro:property name="robot_mechaical_design_offset_y" value="0" />
	<xacro:property name="robot_mechaical_design_offset_z" value="0" />

	<!-- ========================================================================================== -->



	<xacro:property name="camera_mass" value="0.1"/>
	<xacro:property name="hokoyu_mass" value="1e-5"/>

		<!-- Project center to the ground -->
	<link name="robot_footprint">
	        <visual>
            <origin
                    xyz="0 0 0.0"
                    rpy="1.57 0 1.57" />
            <geometry>
                <mesh filename="package://mando_description/meshes/scout_mini/scout_mini_base_link2.dae" />
            </geometry>
        </visual>
        <collision>
            <origin
                    xyz="0 0 0"
                    rpy="1.57 0 1.57" />
          <geometry>
            <mesh
              filename="package://mando_description/meshes/scout_mini/scout_mini_base_link2.dae" />
          </geometry>
        </collision>
	</link>

	<!-- Make Inertia link -->
	<link name="chassis">
        <inertial>
            <mass value="60" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>

	</link>

	<!-- Robot base + Inertia  -->
	<joint name="robot_footprint_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0" />
		<parent link="robot_footprint"/>
		<child link="chassis" />
	</joint>



	<!-- Camera -->
	<link name="camera">
		<inertial>
			<mass value="${camera_mass}"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<inertia
		        ixx="1e-6" ixy="0.0" ixz="0.0"
		        iyy="1e-6" iyz="0.0"
		        izz="1e-6"
		      />
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.05 0.05"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.05 0.05"/>
			</geometry>
		</collision>
	</link>

	<!-- Hokuyo Lidar -->
	<link name="hokuyo">
		<inertial>
			<mass value="${hokoyu_mass}"/>
			<origin xyz="0 0 0" rpy="0 0 0"/>

			<inertia
		        ixx="1e-6" ixy="0.0" ixz="0.0"
		        iyy="1e-6" iyz="0.0"
		        izz="1e-6"
		      />
		</inertial>

		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://mando_gazebo/meshes/hokuyo.dae"/>
			</geometry>
		</visual>

		<collision>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.1 0.1 0.1"/>
			</geometry>
		</collision>
	</link>



	<!-- Camera Joint -->
	<joint name="camera_joint" type="fixed">
		<origin xyz="0.26 0 0" rpy="0 0 0" />
		<parent link="chassis"/>
		<child link="camera" />
		<axis xyz="0 1 0"/>
	</joint>

	<!-- Hokoyu Joint -->
	<joint name="hokuyo_joint" type="fixed">
	    <origin xyz="0.2 0 0.2" rpy="0 0 0" />
	    <parent link="chassis"/>
	    <child link="hokuyo" />  
	    <axis xyz="0 1 0"/> 
	</joint>


	<gazebo reference="camera">
		<!-- <material>Gazebo/Red</material> -->
	</gazebo>

	<gazebo reference="chassis">
		<!-- <material>Gazebo/Blue</material> -->
	</gazebo>




    <!-- Scout wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
    <xacro:scout_mini_wheel_1 wheel_prefix="left_wheel_front">
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel_1>


    <xacro:scout_mini_wheel_2 wheel_prefix="left_wheel_back">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:scout_mini_wheel_2>


    <xacro:scout_mini_wheel_3 wheel_prefix="right_wheel_front">
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel_3>


    <xacro:scout_mini_wheel_4 wheel_prefix="right_wheel_back">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:scout_mini_wheel_4>



	<!-- Motor, Camera and Lidar Simulation -->
	<xacro:include filename="$(find mando_gazebo)/urdf/atom.gazebo" />



</robot>
